name: Nightly E2E Tests
on:
  workflow_dispatch:
  # schedule:
    # * is a special character in YAML so you have to quote this string
    # currently set to run at the end of each day
    # - cron: "0 0 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: "${{ secrets.EXPO_TOKEN }}"
      - name: Install dependencies
        run: npm install
      - name: Build on EAS
        run: eas build --profile preview --platform android --non-interactive --no-wait
